/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Player_apiDotphpRouteImport } from './routes/player_api[.]php'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GetDotphpRouteImport } from './routes/get[.]php'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ApiXmltvRouteImport } from './routes/api/xmltv'
import { Route as ApiPlayer_apiRouteImport } from './routes/api/player_api'
import { Route as ApiMagRouteImport } from './routes/api/mag'
import { Route as ApiGetRouteImport } from './routes/api/get'
import { Route as AdminVodRouteImport } from './routes/admin.vod'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminStreamsRouteImport } from './routes/admin.streams'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminPlaylistsRouteImport } from './routes/admin.playlists'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminApiRouteImport } from './routes/admin.api'

const Player_apiDotphpRoute = Player_apiDotphpRouteImport.update({
  id: '/player_api.php',
  path: '/player_api.php',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GetDotphpRoute = GetDotphpRouteImport.update({
  id: '/get.php',
  path: '/get.php',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiXmltvRoute = ApiXmltvRouteImport.update({
  id: '/api/xmltv',
  path: '/api/xmltv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlayer_apiRoute = ApiPlayer_apiRouteImport.update({
  id: '/api/player_api',
  path: '/api/player_api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMagRoute = ApiMagRouteImport.update({
  id: '/api/mag',
  path: '/api/mag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGetRoute = ApiGetRouteImport.update({
  id: '/api/get',
  path: '/api/get',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVodRoute = AdminVodRouteImport.update({
  id: '/vod',
  path: '/vod',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStreamsRoute = AdminStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiRoute = AdminApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/get.php': typeof GetDotphpRoute
  '/login': typeof LoginRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vod': typeof AdminVodRoute
  '/api/get': typeof ApiGetRoute
  '/api/mag': typeof ApiMagRoute
  '/api/player_api': typeof ApiPlayer_apiRoute
  '/api/xmltv': typeof ApiXmltvRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get.php': typeof GetDotphpRoute
  '/login': typeof LoginRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vod': typeof AdminVodRoute
  '/api/get': typeof ApiGetRoute
  '/api/mag': typeof ApiMagRoute
  '/api/player_api': typeof ApiPlayer_apiRoute
  '/api/xmltv': typeof ApiXmltvRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/get.php': typeof GetDotphpRoute
  '/login': typeof LoginRoute
  '/player_api.php': typeof Player_apiDotphpRoute
  '/admin/api': typeof AdminApiRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/streams': typeof AdminStreamsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vod': typeof AdminVodRoute
  '/api/get': typeof ApiGetRoute
  '/api/mag': typeof ApiMagRoute
  '/api/player_api': typeof ApiPlayer_apiRoute
  '/api/xmltv': typeof ApiXmltvRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/get.php'
    | '/login'
    | '/player_api.php'
    | '/admin/api'
    | '/admin/logs'
    | '/admin/playlists'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/users'
    | '/admin/vod'
    | '/api/get'
    | '/api/mag'
    | '/api/player_api'
    | '/api/xmltv'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get.php'
    | '/login'
    | '/player_api.php'
    | '/admin/api'
    | '/admin/logs'
    | '/admin/playlists'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/users'
    | '/admin/vod'
    | '/api/get'
    | '/api/mag'
    | '/api/player_api'
    | '/api/xmltv'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/get.php'
    | '/login'
    | '/player_api.php'
    | '/admin/api'
    | '/admin/logs'
    | '/admin/playlists'
    | '/admin/resellers'
    | '/admin/settings'
    | '/admin/streams'
    | '/admin/users'
    | '/admin/vod'
    | '/api/get'
    | '/api/mag'
    | '/api/player_api'
    | '/api/xmltv'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GetDotphpRoute: typeof GetDotphpRoute
  LoginRoute: typeof LoginRoute
  Player_apiDotphpRoute: typeof Player_apiDotphpRoute
  ApiGetRoute: typeof ApiGetRoute
  ApiMagRoute: typeof ApiMagRoute
  ApiPlayer_apiRoute: typeof ApiPlayer_apiRoute
  ApiXmltvRoute: typeof ApiXmltvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player_api.php': {
      id: '/player_api.php'
      path: '/player_api.php'
      fullPath: '/player_api.php'
      preLoaderRoute: typeof Player_apiDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get.php': {
      id: '/get.php'
      path: '/get.php'
      fullPath: '/get.php'
      preLoaderRoute: typeof GetDotphpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/xmltv': {
      id: '/api/xmltv'
      path: '/api/xmltv'
      fullPath: '/api/xmltv'
      preLoaderRoute: typeof ApiXmltvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/player_api': {
      id: '/api/player_api'
      path: '/api/player_api'
      fullPath: '/api/player_api'
      preLoaderRoute: typeof ApiPlayer_apiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mag': {
      id: '/api/mag'
      path: '/api/mag'
      fullPath: '/api/mag'
      preLoaderRoute: typeof ApiMagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/get': {
      id: '/api/get'
      path: '/api/get'
      fullPath: '/api/get'
      preLoaderRoute: typeof ApiGetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vod': {
      id: '/admin/vod'
      path: '/vod'
      fullPath: '/admin/vod'
      preLoaderRoute: typeof AdminVodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/streams': {
      id: '/admin/streams'
      path: '/streams'
      fullPath: '/admin/streams'
      preLoaderRoute: typeof AdminStreamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api': {
      id: '/admin/api'
      path: '/api'
      fullPath: '/admin/api'
      preLoaderRoute: typeof AdminApiRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApiRoute: typeof AdminApiRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminResellersRoute: typeof AdminResellersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStreamsRoute: typeof AdminStreamsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVodRoute: typeof AdminVodRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiRoute: AdminApiRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminResellersRoute: AdminResellersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStreamsRoute: AdminStreamsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVodRoute: AdminVodRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GetDotphpRoute: GetDotphpRoute,
  LoginRoute: LoginRoute,
  Player_apiDotphpRoute: Player_apiDotphpRoute,
  ApiGetRoute: ApiGetRoute,
  ApiMagRoute: ApiMagRoute,
  ApiPlayer_apiRoute: ApiPlayer_apiRoute,
  ApiXmltvRoute: ApiXmltvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
